### ISSUE TITLE
With semver a version nummer like `0.0.x` is not expected

### ISSUE THREAD

**Issue by webwurst** [giantswarm/versionbundle#27]
If there has been no release yet, there is nothing to patch. So you should [start your initial development release at `0.1.0`](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)

But we are actually have a [test for `0.0.1`](https://github.com/giantswarm/versionbundle/blob/master/release_test.go#L1389)

Maybe nitpicking, but semver is [semver](https://semver.org/)..

**Comment by xh3b4sd** [comment]
This is because of the aggregation. When you feel better we can say we do not use semver. Just to be correct. We are aggregating release versions anyway and we have a major a minor and a patch level. So what can we do to make you happy here and to close this issue? I do not see what we can do better now. I would favour to iterate from here. I do not want to get distracted from the overall goal, which is automated updates. We can definitely polish anything down the road if there is a need.

**Comment by webwurst** [comment]
Yeah ok, let's see what comes up down the road.
